version: '3.8'

services:
  zookeeper:
    image: confluentinc/cp-zookeeper:7.3.0
    container_name: zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    networks:
      - kafka-network

  broker:
    image: confluentinc/cp-kafka:7.3.0
    container_name: broker
    ports:
      - "9092:9092"
    depends_on:
      - zookeeper
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: 'zookeeper:2181'
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_INTERNAL:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://broker:9092,PLAINTEXT_INTERNAL://broker:29092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
    networks:
      - kafka-network

  producer:
    image: producer
    container_name: producer
    depends_on:
      - broker
    environment:
      RUST_BACKTRACE: 'full'
    networks:
      - kafka-network

  consumer:
    image: consumer
    container_name: consumer
    depends_on:
      - broker
    environment:
      RUST_BACKTRACE: 'full'
    networks:
      - kafka-network

  ping-test:
    image: alpine:latest
    container_name: ping-test
    command: ["ash", "-c", "ping broker"]
    depends_on:
      - broker
    networks:
      - kafka-network

networks:
  kafka-network:
    driver: bridge
